### ISSUE TITLE
Updating to analytics-swift version 1.6.2 causes build error in LivePlugins "Cannot assign to property: 'loaded' is a get-only property"

### ISSUE THREAD

**Issue by seanperez29** [segment-integrations/analytics-swift-filters#4]
Whenever I try to update my analytics-swift library to the latest version 1.6.2:
![Screenshot 2024-11-07 at 7 21 33 PM](https://github.com/user-attachments/assets/c67c410a-0784-4fc5-a508-36df3f527b1f)

I get this build error in the LivePlugins class:
<img width="1289" alt="Screenshot 2024-11-07 at 4 25 43 PM" src="https://github.com/user-attachments/assets/4c6130a8-dd1e-4ce7-9e32-b69059bf4ff3">

I'm running Xcode version 15.4

**Comment by bsneed** [comment]
This should be resolved now per our conversation on another repo.
